import type { Species } from "./types";

export const mockSpeciesDatabase: Species[] = [
  {
    id: "amur-leopard",
    commonName: "Amur Leopard",
    scientificName: "Panthera pardus orientalis",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Temperate Forest", "Russian Far East"],
    conservationStatus: "CR",
    population: "~100 individuals",
    description:
      "The Amur leopard is the world's rarest wild cat. Adapted to cold climates with thick spotted fur, it's an apex predator of the Russian Far East forests. Its solitary nature and vast territory requirements make it especially vulnerable.",
    threats: ["Poaching", "Habitat loss", "Prey depletion", "Inbreeding"],
    howToHelp: [
      "Support WWF's Amur Leopard conservation programs",
      "Avoid purchasing fur products",
      "Raise awareness on social media",
      "Donate to anti-poaching organizations",
    ],
    funFacts: [
      "Can leap more than 6 meters horizontally",
      "Stores food in trees to keep it from other predators",
      "Each leopard has a unique spot pattern",
    ],
    range: "Russian Far East, Northeastern China",
    diet: "Deer, wild boar, small mammals",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Amur_leopard_Panthera_pardus_orientalis.jpg/640px-Amur_leopard_Panthera_pardus_orientalis.jpg",
  },
  {
    id: "vaquita",
    commonName: "Vaquita",
    scientificName: "Phocoena sinus",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Shallow Coastal Waters", "Gulf of California"],
    conservationStatus: "CR",
    population: "<10 individuals",
    description:
      "The vaquita is the world's most critically endangered marine mammal. This small porpoise is endemic to the northern Gulf of California and has been decimated by illegal gillnet fishing.",
    threats: ["Illegal fishing nets (bycatch)", "Illegal totoaba trade", "Pollution"],
    howToHelp: [
      "Support Sea Shepherd's Operation Milagro",
      "Avoid seafood caught in the Gulf of California without certification",
      "Petition for stronger fishing regulations",
      "Donate to the Vaquita CPR program",
    ],
    funFacts: [
      "Spanish for 'little cow'",
      "Smallest cetacean in the world",
      "Uses echolocation to navigate",
    ],
    range: "Northern Gulf of California, Mexico",
    diet: "Fish, squid, crustaceans",
  },
  {
    id: "sumatran-orangutan",
    commonName: "Sumatran Orangutan",
    scientificName: "Pongo abelii",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Tropical Rainforest", "Sumatra"],
    conservationStatus: "CR",
    population: "~14,000 individuals",
    description:
      "The Sumatran orangutan is one of humanity's closest relatives, sharing 96.9% of our DNA. These highly intelligent apes build elaborate nests, use tools, and have complex social cultures passed down through generations.",
    threats: ["Deforestation for palm oil", "Illegal pet trade", "Hunting"],
    howToHelp: [
      "Choose palm-oil-free or certified sustainable palm oil products",
      "Support Sumatran Orangutan Society",
      "Never buy exotic pets",
      "Reduce, reuse, recycle paper and wood products",
    ],
    funFacts: [
      "Have the longest childhood of any animal except humans",
      "Can learn sign language",
      "Name means 'person of the forest' in Malay",
    ],
    range: "Northern Sumatra, Indonesia",
    diet: "Fruit, bark, insects, bird eggs",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Orang_Utan%2C_Semenggok_Forest_Reserve%2C_Sarawak%2C_Borneo%2C_Malaysia.JPG/640px-Orang_Utan%2C_Semenggok_Forest_Reserve%2C_Sarawak%2C_Borneo%2C_Malaysia.JPG",
  },
  {
    id: "snow-leopard",
    commonName: "Snow Leopard",
    scientificName: "Panthera uncia",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Alpine Meadows", "Rocky Terrain", "Central Asia"],
    conservationStatus: "VU",
    population: "4,000–6,500 individuals",
    description:
      "The ghost of the mountains. Snow leopards are perfectly adapted to cold, rugged mountain terrain. Their pale, spotted coats provide camouflage against rocks and snow, and their long tails help them balance.",
    threats: ["Poaching", "Retaliatory killings by herders", "Climate change", "Prey depletion"],
    howToHelp: [
      "Support Snow Leopard Trust programs",
      "Buy handicrafts from Snow Leopard Enterprises cooperatives",
      "Avoid products with big cat fur or bones",
    ],
    funFacts: [
      "Cannot roar — only purr, hiss, and mew",
      "Tails are nearly as long as their bodies",
      "Can kill prey three times their size",
    ],
    range: "12 countries across Central Asia",
    diet: "Blue sheep, ibex, marmots",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Snow_leopard_Panthera_uncia.jpg/640px-Snow_leopard_Panthera_uncia.jpg",
  },
  {
    id: "blue-whale",
    commonName: "Blue Whale",
    scientificName: "Balaenoptera musculus",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Open Ocean", "All Major Oceans"],
    conservationStatus: "EN",
    population: "10,000–25,000 individuals",
    description:
      "The largest animal ever known to have lived on Earth, blue whales can reach 30 meters in length. Despite their immense size, they feed almost exclusively on tiny krill. Their haunting songs travel thousands of miles underwater.",
    threats: ["Ship strikes", "Entanglement in fishing gear", "Ocean pollution", "Climate change affecting krill"],
    howToHelp: [
      "Reduce single-use plastic consumption",
      "Support whale sanctuaries and marine protected areas",
      "Choose sustainably sourced seafood",
      "Support organizations working on shipping lane adjustments",
    ],
    funFacts: [
      "Heart is the size of a small car",
      "Tongue weighs as much as an elephant",
      "Calls can be heard 1,600 km away",
    ],
    range: "All major oceans except Arctic",
    diet: "Krill (up to 40 million per day)",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Sperm_whale_pod.jpg/640px-Sperm_whale_pod.jpg",
  },
  {
    id: "rafflesia-arnoldii",
    commonName: "Rafflesia",
    scientificName: "Rafflesia arnoldii",
    kingdom: "Plantae",
    class: "Magnoliopsida",
    habitat: ["Tropical Rainforest", "Sumatra", "Borneo"],
    conservationStatus: "CR",
    population: "Unknown — severely fragmented",
    description:
      "The largest individual flower on Earth. Rafflesia has no leaves, stems, or roots — it's a purely parasitic plant that lives inside the tissue of its host vine. It blooms for only a few days, emitting a rotting flesh odor to attract pollinators.",
    threats: ["Deforestation", "Habitat fragmentation", "Collection", "Host vine destruction"],
    howToHelp: [
      "Support Indonesian conservation NGOs",
      "Choose sustainable forest products",
      "Advocate for rainforest protection policies",
    ],
    funFacts: [
      "Flowers can weigh up to 11 kg",
      "Takes up to 9 months to develop before blooming",
      "Smells like rotting flesh to attract flies",
    ],
    range: "Sumatra and Borneo, Indonesia",
    diet: "Parasitic — feeds on host vine nutrients",
  },
  {
    id: "monarch-butterfly",
    commonName: "Monarch Butterfly",
    scientificName: "Danaus plexippus",
    kingdom: "Animalia",
    class: "Insecta",
    habitat: ["Meadows", "Fields", "Forests", "North America"],
    conservationStatus: "EN",
    population: "~1.9 billion (90% decline since 1990s)",
    description:
      "Monarchs undertake one of the most spectacular migrations in the animal kingdom — up to 4,800 km from Canada to Mexico. No single butterfly completes the round trip; it takes multiple generations.",
    threats: ["Milkweed loss from herbicide use", "Deforestation of wintering sites", "Climate change", "Pesticides"],
    howToHelp: [
      "Plant native milkweed in your garden",
      "Reduce or eliminate pesticide use",
      "Create waystation habitats",
      "Join citizen science monitoring programs like Journey North",
    ],
    funFacts: [
      "Toxic to predators due to milkweed diet",
      "Navigate using the sun and Earth's magnetic field",
      "Can fly 80–160 km per day during migration",
    ],
    range: "North America (breeding), Mexico (wintering)",
    diet: "Milkweed (larvae), flower nectar (adults)",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Monarch_Butterfly_Danaus_plexippus_Mating_Vertical_3008px.jpg/640px-Monarch_Butterfly_Danaus_plexippus_Mating_Vertical_3008px.jpg",
  },
  {
    id: "pangolin",
    commonName: "Pangolin",
    scientificName: "Manis spp.",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Tropical Forest", "Grasslands", "Africa", "Asia"],
    conservationStatus: "CR",
    population: "Unknown — all 8 species threatened",
    description:
      "The most trafficked mammal in the world. Pangolins are covered in overlapping keratin scales — the only mammal with this feature. When threatened, they roll into a tight ball. They are essential for ecosystem health, consuming millions of ants and termites.",
    threats: ["Illegal wildlife trade (scales & meat)", "Habitat loss", "Hunting"],
    howToHelp: [
      "Never purchase pangolin products",
      "Report illegal wildlife trade to authorities",
      "Support Save Pangolins organization",
      "Spread awareness about their ecological importance",
    ],
    funFacts: [
      "Scales are made of the same material as human fingernails",
      "Have no teeth — grinds food in their stomachs",
      "A single pangolin can eat 70 million insects per year",
    ],
    range: "Sub-Saharan Africa and South/Southeast Asia",
    diet: "Ants, termites",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Pangolin_India.jpg/640px-Pangolin_India.jpg",
  },
  {
    id: "ammospermophilus-nelsoni",
    commonName: "Nelson's Antelope Squirrel",
    scientificName: "Ammospermophilus nelsoni",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Desert"],
    conservationStatus: "Unknown",
    population: "Unknown",
    description: "A small ground squirrel native to arid regions of California.",
    threats: ["Habitat loss"],
    howToHelp: [
      "Support habitat conservation in California desert ecosystems",
      "Advocate for responsible land-use planning in arid habitats",
      "Support native plant restoration projects",
      "Learn about local desert wildlife and share awareness"
    ],
    funFacts: [
      "Adapted to desert heat",
      "It can stay active in very hot environments",
      "It is native to arid regions of California"
    ],
    range: "California",
    diet: "Seeds, insects",
  },
  {
    id: "antilocapra-americana",
    commonName: "Pronghorn",
    scientificName: "Antilocapra americana",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Grasslands"],
    conservationStatus: "LC",
    population: "Stable",
    description: "The fastest land animal in North America.",
    threats: ["Habitat fragmentation"],
    howToHelp: [
      "Support grassland conservation groups",
      "Advocate for wildlife corridors across fenced landscapes",
      "Drive carefully in pronghorn habitat",
      "Support restoration of open rangeland ecosystems"
    ],
    funFacts: [
      "Can run over 55 mph",
      "It is the fastest land animal in North America",
      "It relies on open terrain to spot predators early"
    ],
    range: "North America",
    diet: "Grasses and shrubs",
  },
  {
    id: "arborimus-pomo",
    commonName: "Sonoma Tree Vole",
    scientificName: "Arborimus pomo",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Forest"],
    conservationStatus: "NT",
    population: "Unknown",
    description: "A rare rodent that lives in forest canopies.",
    threats: ["Logging"],
    howToHelp: [
      "Protect mature forest habitat",
      "Support sustainable forestry practices",
      "Advocate for old-growth forest preservation",
      "Support conservation research on rare forest mammals"
    ],
    funFacts: [
      "Lives mostly in trees",
      "It spends much of its life in the forest canopy",
      "It is a rare rodent found in California"
    ],
    range: "California",
    diet: "Conifer needles",
  },
  {
    id: "arctocephalus-townsendi",
    commonName: "Guadalupe Fur Seal",
    scientificName: "Arctocephalus townsendi",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Marine"],
    conservationStatus: "NT",
    population: "Increasing",
    description: "A fur seal native to the Pacific coast.",
    threats: ["Fishing nets"],
    howToHelp: [
      "Support marine mammal protection groups",
      "Choose seafood from sustainable fisheries",
      "Reduce ocean plastic and fishing gear pollution",
      "Support marine protected areas in the Pacific"
    ],
    funFacts: [
      "Once thought extinct",
      "It is native to the Pacific coast",
      "Its population has been increasing"
    ],
    range: "Pacific Ocean",
    diet: "Fish, squid",
  },
  {
    id: "balaenoptera-musculus",
    commonName: "Blue Whale",
    scientificName: "Balaenoptera musculus",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Ocean"],
    conservationStatus: "EN",
    population: "10,000–25,000",
    description: "The largest animal ever to live.",
    threats: ["Ship strikes"],
    howToHelp: [
      "Reduce ocean pollution and plastic waste",
      "Support protections for whale migration routes",
      "Advocate for safer shipping lane policies",
      "Support marine conservation organizations"
    ],
    funFacts: [
      "Heart is the size of a car",
      "It is the largest animal ever known to have lived",
      "It mainly feeds on tiny krill"
    ],
    range: "Global oceans",
    diet: "Krill",
  },
  {
    id: "balaenoptera-physalus",
    commonName: "Fin Whale",
    scientificName: "Balaenoptera physalus",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Ocean"],
    conservationStatus: "VU",
    population: "Unknown",
    description: "The second-largest whale species.",
    threats: ["Whaling", "Ship strikes"],
    howToHelp: [
      "Support international whale conservation efforts",
      "Advocate for reduced ship speeds in whale habitat",
      "Reduce demand for products tied to ocean degradation",
      "Support marine protected areas"
    ],
    funFacts: [
      "Very fast swimmer",
      "It is the second-largest whale species",
      "It lives throughout the world's oceans"
    ],
    range: "Global oceans",
    diet: "Krill, fish",
  },
  {
    id: "callorhinus-ursinus",
    commonName: "Northern Fur Seal",
    scientificName: "Callorhinus ursinus",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Marine"],
    conservationStatus: "VU",
    population: "Declining",
    description: "A migratory marine mammal.",
    threats: ["Fishing nets"],
    howToHelp: [
      "Support ocean conservation efforts in the North Pacific",
      "Choose sustainably caught seafood",
      "Reduce marine debris and plastic waste",
      "Support research on marine mammal migration and bycatch"
    ],
    funFacts: [
      "Migrates long distances",
      "It is a marine mammal of the North Pacific",
      "Its population has been declining"
    ],
    range: "North Pacific",
    diet: "Fish, squid",
  },
  {
    id: "canis-lupus",
    commonName: "Gray Wolf",
    scientificName: "Canis lupus",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Forests", "Tundra"],
    conservationStatus: "LC",
    population: "Stable",
    description: "A keystone predator with complex social structure.",
    threats: ["Persecution"],
    howToHelp: [
      "Support science-based predator conservation policies",
      "Protect large connected wild habitats",
      "Support coexistence programs for ranchers and wolves",
      "Learn about wolves and counter harmful myths"
    ],
    funFacts: [
      "Lives in packs",
      "It is a keystone predator",
      "Gray wolves have complex social behavior"
    ],
    range: "North America, Eurasia",
    diet: "Large herbivores",
  },
  {
    id: "choeronycteris-mexicana",
    commonName: "Mexican Long-tongued Bat",
    scientificName: "Choeronycteris mexicana",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Desert", "Caves"],
    conservationStatus: "NT",
    population: "Unknown",
    description: "A nectar-feeding bat important for pollination.",
    threats: ["Habitat loss"],
    howToHelp: [
      "Protect cave roosting sites",
      "Plant native flowering species that support pollinators",
      "Reduce pesticide use near bat habitat",
      "Support bat conservation and pollinator education programs"
    ],
    funFacts: [
      "Pollinates agave plants",
      "It feeds mainly on nectar",
      "It helps desert ecosystems through pollination"
    ],
    range: "Mexico, southwestern US",
    diet: "Nectar",
  },
  {
    id: "corynorhinus-townsendii",
    commonName: "Townsend's Big-eared Bat",
    scientificName: "Corynorhinus townsendii",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Caves", "Forests"],
    conservationStatus: "NT",
    population: "Unknown",
    description: "A bat species known for its large ears.",
    threats: ["Disturbance of roosts"],
    howToHelp: [
      "Protect cave and mine roosting sites",
      "Avoid disturbing bat colonies during roosting season",
      "Support habitat protection in forested areas",
      "Educate others about the importance of bats"
    ],
    funFacts: [
      "Ears nearly as long as body",
      "It is known for its distinctive large ears",
      "It relies on caves and forest habitats"
    ],
    range: "North America",
    diet: "Insects",
  },
  {
    id: "dipodomys-ingens",
    commonName: "Giant Kangaroo Rat",
    scientificName: "Dipodomys ingens",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Grasslands"],
    conservationStatus: "EN",
    population: "Declining",
    description: "A large kangaroo rat endemic to California.",
    threats: ["Agriculture"],
    howToHelp: [
      "Protect native grassland habitat in California",
      "Support restoration of arid grassland ecosystems",
      "Advocate for wildlife-friendly agricultural practices",
      "Support endangered species conservation programs"
    ],
    funFacts: [
      "Can leap long distances",
      "It is endemic to California",
      "It is one of the largest kangaroo rat species"
    ],
    range: "California",
    diet: "Seeds",
  },
  {
    id: "dipodomys-nitratoides",
    commonName: "Fresno Kangaroo Rat",
    scientificName: "Dipodomys nitratoides",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Desert"],
    conservationStatus: "EN",
    population: "Unknown",
    description: "A rare kangaroo rat species.",
    threats: ["Habitat destruction"],
    howToHelp: [
      "Support conservation of desert and scrub habitats",
      "Advocate against unchecked land conversion",
      "Support endangered rodent monitoring programs",
      "Learn about and share awareness of lesser-known species"
    ],
    funFacts: [
      "Nocturnal",
      "It is a rare kangaroo rat species",
      "It is adapted to dry California habitats"
    ],
    range: "California",
    diet: "Seeds",
  },
  {
    id: "dipodomys-stephensi",
    commonName: "Stephens' Kangaroo Rat",
    scientificName: "Dipodomys stephensi",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Grasslands"],
    conservationStatus: "EN",
    population: "Declining",
    description: "A threatened rodent species.",
    threats: ["Urbanization"],
    howToHelp: [
      "Protect remaining grassland habitat",
      "Support land management that preserves native vegetation",
      "Advocate for smart growth that limits habitat loss",
      "Support endangered species recovery efforts"
    ],
    funFacts: [
      "Efficient water conservation",
      "It is adapted to survive in dry environments",
      "It is threatened by expanding urban development"
    ],
    range: "California",
    diet: "Seeds",
  },
  {
    id: "enhydra-lutris",
    commonName: "Sea Otter",
    scientificName: "Enhydra lutris",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Coastal waters"],
    conservationStatus: "EN",
    population: "Stable",
    description: "A marine mammal known for using tools.",
    threats: ["Oil spills"],
    howToHelp: [
      "Support marine conservation along the Pacific coast",
      "Reduce plastic and chemical pollution entering waterways",
      "Advocate for oil spill prevention and response planning",
      "Support kelp forest ecosystem protection"
    ],
    funFacts: [
      "Uses rocks to open shells",
      "It is one of the few mammals known to use tools",
      "Sea otters help maintain healthy kelp forests"
    ],
    range: "Pacific Coast",
    diet: "Sea urchins, shellfish",
  },
  {
    id: "erethizon-dorsatum",
    commonName: "North American Porcupine",
    scientificName: "Erethizon dorsatum",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Forests"],
    conservationStatus: "LC",
    population: "Stable",
    description: "A rodent covered in protective quills.",
    threats: ["Road mortality"],
    howToHelp: [
      "Drive carefully in wildlife areas",
      "Support forest habitat conservation",
      "Promote wildlife crossings in roaded areas",
      "Educate others not to harass wild animals"
    ],
    funFacts: [
      "Quills detach easily",
      "It is one of North America's best-known quilled mammals",
      "It mainly eats plant material such as bark and leaves"
    ],
    range: "North America",
    diet: "Bark, leaves",
  },
  {
    id: "eschrichtius-robustus",
    commonName: "Gray Whale",
    scientificName: "Eschrichtius robustus",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Ocean"],
    conservationStatus: "LC",
    population: "Recovered",
    description: "A whale known for long migrations.",
    threats: ["Ship strikes"],
    howToHelp: [
      "Support protections for whale migration corridors",
      "Advocate for safer shipping practices",
      "Reduce ocean pollution",
      "Support responsible whale-watching guidelines"
    ],
    funFacts: [
      "Migrates thousands of miles",
      "It is known for long coastal migrations",
      "It feeds on bottom-dwelling invertebrates"
    ],
    range: "Pacific Ocean",
    diet: "Bottom-dwelling invertebrates",
  },
  {
    id: "eumetopias-jubatus",
    commonName: "Steller Sea Lion",
    scientificName: "Eumetopias jubatus",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Coastal"],
    conservationStatus: "NT",
    population: "Recovering",
    description: "The largest sea lion species.",
    threats: ["Fishing competition"],
    howToHelp: [
      "Support sustainable fishing policies",
      "Protect coastal haul-out and breeding sites",
      "Reduce marine pollution and debris",
      "Support marine mammal monitoring programs"
    ],
    funFacts: [
      "Males much larger than females",
      "It is the largest sea lion species",
      "It lives around coasts in the North Pacific"
    ],
    range: "North Pacific",
    diet: "Fish, squid",
  },
  {
    id: "lasiurus-cinereus",
    commonName: "Hoary Bat",
    scientificName: "Lasiurus cinereus",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Forests"],
    conservationStatus: "LC",
    population: "Stable",
    description: "A migratory bat species.",
    threats: ["Wind turbines"],
    howToHelp: [
      "Support bat-friendly wind energy policies",
      "Protect roosting and migratory habitat",
      "Reduce pesticide use that lowers insect prey",
      "Support bat research and monitoring"
    ],
    funFacts: [
      "Migrates long distances",
      "It is a migratory bat species",
      "Its diet consists mainly of insects"
    ],
    range: "Americas",
    diet: "Insects",
  },
  {
    id: "martes-caurina",
    commonName: "Pacific Marten",
    scientificName: "Martes caurina",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Forests"],
    conservationStatus: "NT",
    population: "Unknown",
    description: "A small carnivorous mammal.",
    threats: ["Habitat loss"],
    howToHelp: [
      "Protect mature forest habitat",
      "Support wildlife-friendly forest management",
      "Reduce use of poisons that affect food webs",
      "Support research on rare forest carnivores"
    ],
    funFacts: [
      "Excellent climber",
      "It is a small carnivorous mammal",
      "It lives in forests of western North America"
    ],
    range: "Western North America",
    diet: "Small mammals",
  },
  {
    id: "megaptera-novaeangliae",
    commonName: "Humpback Whale",
    scientificName: "Megaptera novaeangliae",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Ocean"],
    conservationStatus: "LC",
    population: "Recovering",
    description: "Known for acrobatic breaches and songs.",
    threats: ["Entanglement"],
    howToHelp: [
      "Support efforts to reduce fishing gear entanglement",
      "Advocate for ocean conservation and marine reserves",
      "Choose seafood from sustainable sources",
      "Follow responsible whale-watching practices"
    ],
    funFacts: [
      "Complex songs",
      "It is famous for breaching out of the water",
      "Its population has been recovering in many regions"
    ],
    range: "Global oceans",
    diet: "Krill, fish",
  },
  {
    id: "mirounga-angustirostris",
    commonName: "Northern Elephant Seal",
    scientificName: "Mirounga angustirostris",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Coastal"],
    conservationStatus: "LC",
    population: "Recovered",
    description: "A large seal with a trunk-like nose.",
    threats: ["Historic hunting"],
    howToHelp: [
      "Protect coastal breeding and resting beaches",
      "Give seals space when visiting shorelines",
      "Support marine protected areas",
      "Learn about conservation success stories and share them"
    ],
    funFacts: [
      "Deep divers",
      "It has a distinctive trunk-like nose",
      "Its population recovered after severe historic hunting"
    ],
    range: "Pacific Coast",
    diet: "Fish, squid",
  },
  {
    id: "myotis-lucifugus",
    commonName: "Little Brown Bat",
    scientificName: "Myotis lucifugus",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Forests", "Caves"],
    conservationStatus: "EN",
    population: "Declining",
    description: "A common bat species affected by disease.",
    threats: ["White-nose syndrome"],
    howToHelp: [
      "Support bat conservation programs",
      "Avoid disturbing caves used by bats",
      "Install bat houses where appropriate",
      "Reduce pesticide use to protect insect prey"
    ],
    funFacts: [
      "Eats thousands of insects nightly",
      "It has been heavily affected by white-nose syndrome",
      "It commonly roosts in caves and forested areas"
    ],
    range: "North America",
    diet: "Insects",
  },
  {
    id: "ochotona-princeps",
    commonName: "American Pika",
    scientificName: "Ochotona princeps",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Alpine"],
    conservationStatus: "LC",
    population: "Stable",
    description: "A small alpine mammal sensitive to heat.",
    threats: ["Climate change"],
    howToHelp: [
      "Support climate action and emissions reduction",
      "Protect alpine and mountain habitats",
      "Support research on climate-sensitive species",
      "Visit mountain habitats responsibly"
    ],
    funFacts: [
      "Stores food for winter",
      "It is highly sensitive to heat",
      "It lives in alpine environments in western North America"
    ],
    range: "Western North America",
    diet: "Plants",
  },
  {
    id: "taxidea-taxus",
    commonName: "American Badger",
    scientificName: "Taxidea taxus",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Grasslands"],
    conservationStatus: "LC",
    population: "Stable",
    description: "A burrowing carnivore.",
    threats: ["Habitat loss"],
    howToHelp: [
      "Protect native grasslands and open habitat",
      "Support wildlife-friendly land management",
      "Drive carefully in areas with active wildlife",
      "Support conservation of burrowing mammal ecosystems"
    ],
    funFacts: [
      "Powerful digger",
      "It is a burrowing carnivore",
      "It mainly hunts rodents in open habitats"
    ],
    range: "North America",
    diet: "Rodents",
  },
  {
    id: "tursiops-truncatus",
    commonName: "Bottlenose Dolphin",
    scientificName: "Tursiops truncatus",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Ocean"],
    conservationStatus: "LC",
    population: "Stable",
    description: "Highly intelligent marine mammal.",
    threats: ["Pollution"],
    howToHelp: [
      "Reduce plastic use and litter",
      "Support clean ocean initiatives",
      "Choose sustainably sourced seafood",
      "Respect wild dolphins and avoid harmful tourism practices"
    ],
    funFacts: [
      "Uses echolocation",
      "It is known for high intelligence and social behavior",
      "It lives in oceans around the world"
    ],
    range: "Global oceans",
    diet: "Fish",
  },
  {
    id: "xerospermophilus-mohavensis",
    commonName: "Mojave Ground Squirrel",
    scientificName: "Xerospermophilus mohavensis",
    kingdom: "Animalia",
    class: "Mammalia",
    habitat: ["Desert"],
    conservationStatus: "NT",
    population: "Declining",
    description: "A rare desert squirrel.",
    threats: ["Habitat loss"],
    howToHelp: [
      "Support Mojave Desert habitat conservation",
      "Advocate for responsible development in desert ecosystems",
      "Support native plant restoration in arid landscapes",
      "Raise awareness about lesser-known desert species"
    ],
    funFacts: [
      "Hibernates",
      "It is a rare squirrel of the Mojave region",
      "It is adapted to survive in desert environments"
    ],
    range: "California",
    diet: "Seeds, plants",
  },
  {
  id: "lasionycteris-noctivagans",
  commonName: "Silver-haired Bat",
  scientificName: "Lasionycteris noctivagans",
  kingdom: "Animalia",
  class: "Mammalia",
  habitat: ["Forests"],
  conservationStatus: "LC",
  population: "Stable",
  description: "A migratory bat with dark fur tipped in silver-white.",
  threats: ["Habitat loss", "Wind turbines"],
  howToHelp: ["Protect forests", "Support bat-friendly energy policies"],
  funFacts: ["Named for the silver frosting on its fur"],
  range: "North America",
  diet: "Insects",
},
{
  id: "neotamias-alpinus",
  commonName: "Alpine Chipmunk",
  scientificName: "Neotamias alpinus",
  kingdom: "Animalia",
  class: "Mammalia",
  habitat: ["Alpine", "Mountain talus"],
  conservationStatus: "NT",
  population: "Declining",
  description: "A small chipmunk found in high-elevation Sierra Nevada habitat.",
  threats: ["Climate change", "Habitat shift"],
  howToHelp: ["Support climate action", "Protect alpine habitats"],
  funFacts: ["Lives at higher elevations than many other chipmunks"],
  range: "Sierra Nevada, California",
  diet: "Seeds, plants, insects",
},
{
  id: "pekania-pennanti",
  commonName: "Fisher",
  scientificName: "Pekania pennanti",
  kingdom: "Animalia",
  class: "Mammalia",
  habitat: ["Forests"],
  conservationStatus: "LC",
  population: "Stable",
  description: "A secretive forest carnivore known for agility and climbing ability.",
  threats: ["Habitat fragmentation", "Rodenticides"],
  howToHelp: ["Protect mature forests", "Reduce poison use in wildland areas"],
  funFacts: ["Despite the name, fishers do not mainly eat fish"],
  range: "North America",
  diet: "Small mammals, birds, carrion",
},
{
  id: "perognathus-inornatus",
  commonName: "San Joaquin Pocket Mouse",
  scientificName: "Perognathus inornatus",
  kingdom: "Animalia",
  class: "Mammalia",
  habitat: ["Grasslands", "Desert scrub"],
  conservationStatus: "NT",
  population: "Unknown",
  description: "A small nocturnal rodent adapted to dry habitats in California.",
  threats: ["Agriculture", "Habitat loss"],
  howToHelp: ["Protect native grasslands", "Support habitat restoration"],
  funFacts: ["Carries seeds in fur-lined cheek pouches"],
  range: "California",
  diet: "Seeds, small plant material",
},
{
  id: "physeter-macrocephalus",
  commonName: "Sperm Whale",
  scientificName: "Physeter macrocephalus",
  kingdom: "Animalia",
  class: "Mammalia",
  habitat: ["Deep Ocean"],
  conservationStatus: "VU",
  population: "Unknown",
  description: "The largest toothed whale, famous for deep dives and powerful echolocation.",
  threats: ["Entanglement", "Ship strikes", "Ocean noise"],
  howToHelp: ["Support marine protected areas", "Reduce ocean pollution"],
  funFacts: ["Can dive more than 1,000 meters deep"],
  range: "Global oceans",
  diet: "Squid, fish",
},
{
  id: "pseudorca-crassidens",
  commonName: "False Killer Whale",
  scientificName: "Pseudorca crassidens",
  kingdom: "Animalia",
  class: "Mammalia",
  habitat: ["Open Ocean", "Tropical waters"],
  conservationStatus: "NT",
  population: "Unknown",
  description: "A highly social dolphin species despite its whale-like common name.",
  threats: ["Bycatch", "Pollution", "Noise disturbance"],
  howToHelp: ["Support sustainable fishing", "Reduce marine pollution"],
  funFacts: ["Often forms strong social bonds within pods"],
  range: "Tropical and subtropical oceans",
  diet: "Fish, squid",
},
{
  id: "reithrodontomys-raviventris",
  commonName: "Salt Marsh Harvest Mouse",
  scientificName: "Reithrodontomys raviventris",
  kingdom: "Animalia",
  class: "Mammalia",
  habitat: ["Salt marsh"],
  conservationStatus: "EN",
  population: "Declining",
  description: "A small mouse endemic to San Francisco Bay tidal marshes.",
  threats: ["Habitat loss", "Sea level rise", "Marsh degradation"],
  howToHelp: ["Protect wetlands", "Support marsh restoration projects"],
  funFacts: ["Can swim and tolerate salty environments"],
  range: "San Francisco Bay Area, California",
  diet: "Seeds, plants, small insects",
},
{
  id: "urocyon-littoralis",
  commonName: "Island Fox",
  scientificName: "Urocyon littoralis",
  kingdom: "Animalia",
  class: "Mammalia",
  habitat: ["Coastal scrub", "Woodland", "Island habitats"],
  conservationStatus: "NT",
  population: "Recovering",
  description: "A small fox native to California's Channel Islands.",
  threats: ["Disease", "Introduced predators", "Habitat disturbance"],
  howToHelp: ["Support Channel Islands conservation", "Prevent invasive species spread"],
  funFacts: ["One of the smallest foxes in North America"],
  range: "California Channel Islands",
  diet: "Insects, fruit, small animals",
}
];

export function findSpeciesById(id: string): Species | undefined {
  return mockSpeciesDatabase.find((s) => s.id === id);
}

export function searchSpecies(query: string): Species[] {
  const q = query.toLowerCase();
  return mockSpeciesDatabase.filter(
    (s) =>
      s.commonName.toLowerCase().includes(q) ||
      s.scientificName.toLowerCase().includes(q) ||
      s.conservationStatus.toLowerCase().includes(q)
  );
}
